---
threads: 5
fastqdir: "/home/mgalland/workspace/neurofjacobs/data/01.seqruns/20160912_dopamine_spheres/"
samples:
  mDA_D0_1:
    forward: huESC_fj74_R1.fastq
    reverse: huESC_fj74_R2.fastq
  mDA_D0_2:
    forward: fj95_TGACCA_R1.fastq
    reverse: fj95_TGACCA_R2.fastq
  mDA_D0_3:
    forward: fj96_ACAGTG_R1.fastq
    reverse: fj96_ACAGTG_R2.fastq
  mDA_D28_1:
    forward: C9JBWANXX_102867-001-001_GTCCTAAG_L008_R1.fastq
    reverse: C9JBWANXX_102867-001-001_GTCCTAAG_L008_R2.fastq
  mDA_D28_2:
    forward: C9JBWANXX_102867-001-002_GCGTTAGA_L008_R1.fastq 
    reverse: C9JBWANXX_102867-001-002_GCGTTAGA_L008_R2.fastq
  mDA_D28_3:
    forward: C9JBWANXX_102867-001-003_CAAGGTAC_L008_R1.fastq
    reverse: C9JBWANXX_102867-001-003_CAAGGTAC_L008_R2.fastq
  mDA_D42_1:
    forward: C9JBWANXX_102867-001-004_AGACCTTG_L008_R1.fastq
    reverse: C9JBWANXX_102867-001-004_AGACCTTG_L008_R2.fastq
  mDA_D42_2:
    forward: C9JBWANXX_102867-001-005_GTCGTTAC_L008_R1.fastq
    reverse: C9JBWANXX_102867-001-005_GTCGTTAC_L008_R2.fastq
  mDA_D42_3:
    forward: C9JBWANXX_102867-001-006_GTAACCGA_L008_R1.fastq
    reverse: C9JBWANXX_102867-001-006_GTAACCGA_L008_R2.fastq
trimmomatic:
  adapters: "/zfs/datastore0/software/src/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"
  jarfile: "/zfs/datastore0/software/src/Trimmomatic-0.36/trimmomatic-0.36.jar"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  # phred for illumina >1.8 the quality score are encoded by phred33
  phred: "-phred33"
fastqc:
  executable: '../../scr/FastQC/fastqc'
refseqs:
  genome2bit: '../../data/02.refs/hg19.2bit'
  genomefasta: '../../data/02.refs/hg19.genome.fa'
  chromSizes: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes'
annotations:
  gtf4genes: '../../data/02.refs/knownGenes.gtf'
  gtf4repeats: '../../data/02.refs/repeats.gtf'
  refseqFromSubread: '../../data/02.refs/hg19_RefSeq_exon.txt'
star:
  # alignment will be output only if it has less mismatches than this number
  mismatches: '2'
  # unmapped accepted values are None or Fastx (to output fastq files of unmapped reads)
  unmapped: 'None' 
  # maximum number of loci the read is allowed to map to
  multimappers: '10'
  # alignment will be output if percentage of read length is higher than this value (66% of 2x100bp = 132 nucleotides)
  matchminoverlengthread: '0.66'
