channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - samtools=1.5
  - snakemake=3.8.2
  - pyyaml=3.11
  - subread=1.5.0p3
  - fastqc=0.11.5
  - bedtools=2.26.0
  - ucsc-bedsort=332
  - ucsc-bedgraphtobigwig=332 
  - hisat2=2.1.0
